### ISSUE TITLE
Is documentation complete?

### ISSUE THREAD

**Issue by Otann** [MasturMynd/Pandoras_Box#18]
I was wondering, whether the documentation in PDF is completed or is it still in progress?

I could not find the A and E extrusions specs. My understanding that E extrusion is same as in the standard V0?

And is the page 127 the last one?

**Comment by tiditidi** [comment]
Nah the document kinda stops there, and I believe the extrusions were a bit incomplete as well. I remember having to look at the cad to make certain a few times

I don't remember if they match, but looking at the cad is the best way to tell for sure. Might as well get comfy with the cad since that is the only way to finish out the build atm

Not sure if there is more work happening on the pdf

**Comment by MasturMynd** [comment]
I really need to dig into the manual. A friend was working on it for me but got busy with school and life so they haven't been able to get anything further done. I'll likely end up having to do a rewrite since I don't have their source files and that probably won't be able to happen until either after RMRRF or MRRF.

**Comment by Drmcshorty** [comment]
Are there any updates on the manual being continued?

**Comment by MasturMynd** [comment]
Not likely. The remaining steps are easy to complete with a quick look at the CAD. The author of the manual simply doesn't have time and I'm already working quickly through R3, so it doesn't really make sense for me to rewrite the entire manual at this point. I'll be handling documentation for R3, which will be ready before release.
